[package]
name = "parity"
version = "0.1.0"
edition = "2021"
authors = [ "Yury Shvedov <mestofel13@gmail.com>" ]

[dependencies]
futures = "0.3"
num = "0.4"
tokio = { version = "1", features = [ "full" ] }
async-trait = "0.1.78"
